### PR TITLE
Added new factions name ban system to readme.md

### PR DESCRIPTION
**Pull request by MrBlasyMSK**

### CODE REVIEW

**Comment by ShockedPlot7560** [comment]
where is the mistake ? you want to add a code already present

**Comment by ShockedPlot7560** [comment]
where is the mistake ? you want to add a code already present

**Comment by MrBlasyMSK** [comment]
> where is the mistake ? you want to add a code already present

I am adding the things from the new config.yml to the readme.md which is outdated

**Comment by ShockedPlot7560** [comment]
README.md will be updated when a new release will be published.

**Pull request closed without merging**
